### ISSUE TITLE
Error when downloading the ECMWF HRES data

### ISSUE THREAD

**Issue by xhuang-jpl** [insarlab/PyAPS#23]
Hi, I try to download the ECMWF HRES data through the API as the code shown below,

```
import pyaps3 as pa

date_ref = '20120419'
hr_ref = '16'
date_second = '20121105'
hr_second = '22'
snwe = [38,40,-124,-121]

filedir = '/scratch/test'

#Download the ECMWF data
grb_file_ref = pa.ECMWFdload([date_ref], hr=hr_ref, filedir=filedir, datatype = 'an', model='HRES', snwe=snwe)
grb_file_second = pa.ECMWFdload([date_second], hr=hr_second, filedir=filedir, datatype = 'an', model='HRES', snwe=snwe)
```

there is an error showing no module named `pa`

```
Traceback (most recent call last):
  File "/scratch/xhuang/isce3_test/SanAndreas/donwload.py", line 12, in <module>
    grb_file_ref = pa.ECMWFdload([date_ref], hr=hr_ref, filedir=filedir, datatype = 'an', model='HRES', snwe=snwe)[0]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/xhuang/python/miniconda3/envs/isce3/lib/python3.11/site-packages/pyaps3/autoget.py", line 139, in ECMWFdload
    from pa.ecmwfapi import ECMWFDataServer
ModuleNotFoundError: No module named 'pa'
```

Thank you!

**Comment by scottstanie** [comment]
Ah sorry, I didn't actually test whether it would work because I had been hearing people say how slow the download was this week.

**Comment by xhuang-jpl** [comment]
I also heard similar things from ppl in the RAiDER team. In addition, the HRES is also not free access. I thought it was free when I did this test.

**Comment by yunjunz** [comment]
> the HRES is also not free access.

Yeah, it looks like so: https://www.ecmwf.int/en/forecasts/accessing-forecasts. Thanks for the info @xhuang-jpl. I think we could close this issue now.
